[news]
title = "지디넷코리아 ─ 뉴스 ─ 최신 뉴스"
url = "https://zdnet.co.kr/news/?lstcode=0000&page=1"
entrySelector = "div.news_box div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitUntil = "networkidle"

[news_broadcast]
title = "지디넷코리아 ─ 뉴스 ─ 방송/통신"
url = "https://zdnet.co.kr/news/?lstcode=0000&page=1"
entrySelector = "div:nth-child(4) div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitUntil = "networkidle"

[news_computing]
title = "지디넷코리아 ─ 뉴스 ─ 컴퓨팅"
url = "https://zdnet.co.kr/news/?lstcode=0020&page=1"
entrySelector = "div:nth-child(4) div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitUntil = "networkidle"

[news_mobile]
title = "지디넷코리아 ─ 뉴스 ─ 모바일"
url = "https://zdnet.co.kr/news/?lstcode=0030&page=1"
entrySelector = "div:nth-child(4) div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitUntil = "networkidle"

[news_computing]
title = "지디넷코리아 ─ 뉴스 ─ 컴퓨팅"
url = "https://zdnet.co.kr/news/?lstcode=0020&page=1"
entrySelector = "div:nth-child(4) div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitUntil = "networkidle"



