[default]
timeout = 300

[news]
title = "지디넷코리아 ─ 뉴스 ─ 최신 뉴스"
url = "https://zdnet.co.kr/news/?lstcode=0000&page=1"
entrySelector = "div.news_box div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.news_box div.newsPost"

[news_broadcast]
title = "지디넷코리아 ─ 뉴스 ─ 방송/통신"
url = "https://zdnet.co.kr/news/?lstcode=0010&page=1"
entrySelector = "div.news_box:nth-of-type(2) div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.newsPost"

[news_computing]
title = "지디넷코리아 ─ 뉴스 ─ 컴퓨팅"
url = "https://zdnet.co.kr/news/?lstcode=0020&page=1"
entrySelector = "div.news_box:nth-of-type(2) div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.newsPost"

[news_mobile]
title = "지디넷코리아 ─ 뉴스 ─ 모바일"
url = "https://zdnet.co.kr/news/?lstcode=0030&page=1"
entrySelector = "div.news_box:nth-of-type(2) div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.newsPost"

[news_internet]
title = "지디넷코리아 ─ 뉴스 ─ 인터넷"
url = "https://zdnet.co.kr/news/?lstcode=0040&page=1"
entrySelector = "div.news_box:nth-of-type(2) div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.newsPost"

[news_display]
title = "지디넷코리아 ─ 뉴스 ─ 반도체/디스플레이"
url = "https://zdnet.co.kr/news/?lstcode=0050&page=1"
entrySelector = "div.news_box:nth-of-type(2) div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.newsPost"

[news_cartech]
title = "지디넷코리아 ─ 뉴스 ─ 카테크"
url = "https://zdnet.co.kr/news/?lstcode=0057&page=1"
entrySelector = "div.news_box:nth-of-type(2) div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.newsPost"

[news_healthcare]
title = "지디넷코리아 ─ 뉴스 ─ 헬스케어"
url = "https://zdnet.co.kr/news/?lstcode=0058&page=1"
entrySelector = "div.news_box:nth-of-type(2) div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.newsPost"

[issueplus]
title = "지디넷코리아 ─ 이슈진단+"
url = "https://zdnet.co.kr/special/issueplus.asp"
entrySelector = "div.left_cont.special section.news_box.special_box div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetText a"
contentSelector = "div.assetText a p.summary"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "section.news_box.special_box div.newsPost"

[metaverse]
title = "지디넷코리아 ─ 메타버스"
url = "https://zdnet.co.kr/newskey/?lstcode=%EB%A9%94%ED%83%80%EB%B2%84%EC%8A%A4"
entrySelector = "div.news_box div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.news_box div.newsPost"

[governance]
title = "지디넷코리아 ─ 거버넌스"
url = "https://zdnet.co.kr/newskey/?lstcode=%EB%A9%94%ED%83%80%EB%B2%84%EC%8A%A4"
entrySelector = "div.news_box div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.news_box div.newsPost"

[column]
title = "지디넷코리아 ─ 전문가 칼럼"
url = "https://zdnet.co.kr/column/?lstcode=0100&page=1"
entrySelector = "div.news_box div.newsPost.column2"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
dateSelector = "p.byline span"
dataFormat = "yyyy.MM.dd a hh:mm"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.newsPost.column2"

[news_startup]
title = "지디넷코리아 ─ 중기&스타트업"
url = "https://zdnet.co.kr/news/?lstcode=0045&page=1"
entrySelector = "div.news_box div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
dateSelector = "p.byline span"
dataFormat = "yyyy.MM.dd a hh:mm"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.news_box div.newsPost"

[news_distribution]
title = "지디넷코리아 ─ 유통"
url = "https://zdnet.co.kr/news/?lstcode=0055&page=1"
entrySelector = "div.news_box div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
dateSelector = "p.byline span"
dataFormat = "yyyy.MM.dd a hh:mm"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.news_box div.newsPost"

[news_finance]
title = "지디넷코리아 ─ 금융"
url = "https://zdnet.co.kr/news/?lstcode=0073&page=1"
entrySelector = "div.news_box div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
dateSelector = "p.byline span"
dataFormat = "yyyy.MM.dd a hh:mm"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.news_box div.newsPost"

[news_science]
title = "지디넷코리아 ─ 과학"
url = "https://zdnet.co.kr/news/?lstcode=0070&page=1"
entrySelector = "div.news_box div.newsPost"
titleSelector = "div.assetText a h3"
linkSelector = "div.assetThumb a"
contentSelector = "div.assetText a p"
dateSelector = "p.byline span"
dataFormat = "yyyy.MM.dd a hh:mm"
imageSelector = "div.assetThumb a figure.img img"
waitForSelector = "div.news_box div.newsPost"
